# phpmy admin
version: "3.8"
services:
  cashbackdb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    networks:
      - cashback-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 2s
      interval: 2s
      timeout: 2s
      retries: 55

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: ${DB_HOST}
    networks:
      - cashback-network

  back:
    build: ./back
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./back/prisma:/usr/src/app/prisma
      - ./back/src:/usr/src/app/src
      - ./back/package.json:/usr/src/app/package.json
      - ./back/tsconfig.json:/usr/src/app/tsconfig.json
      - client_volume:/usr/src/app/build/client
      - tpe_volume:/usr/src/app/build/tpe
    depends_on:
      cashbackdb:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}
      - PORT=${PORT}
      - CHOKIDAR_USEPOLLING=true # use for the hot reload when in development
    networks:
      - cashback-network

  tpe:
    platform: linux/x86_64
    build: ./tpe
    depends_on:
      - back
    volumes:
      - tpe_volume:/app/build-apk/

  front:
    platform: linux/x86_64
    build: ./front
    depends_on:
      - back
    volumes:
      - client_volume:/app/build-apk/

networks:
  cashback-network:
volumes:
  client_volume:
  tpe_volume:
