#!/bin/sh

# Obtenir l'adresse IP locale
IP=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')

# Générer le fichier .env
echo "API_URL=$IP:8080" > .env

# Afficher l'adresse IP locale
echo "Adresse IP locale: $IP"