name: Vitest Coverage and Threshold Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-back
        with:
          path: |
            ./back/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-back-${{ hashFiles('./back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-back-

      - name: Install dependencies
        run: cd back && yarn install

      - name: Checking linter
        run: |
          cd ./back
          yarn lint

      - name: Checking typings
        run: |
          cd ./back
          yarn tsc

      - name: Run Vitest tests with coverage
        run: cd back && yarn test:unit

      - name: Build the back
        run: cd back && yarn build
