name: Build front

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create front apk
        run: |
          cd ./front && yarn install
          cd android && chmod +x gradlew && ./gradlew assembleDebug
